### ISSUE TITLE
syntax highlighting not working in mac vscode?

### ISSUE THREAD

**Issue by bonhomie** [Bizcuit/vscode-ampscript#1]
I've installed the extension however it doesn't seem to render the highlights for *.html pages

Is there something which is conflicting with the highlighting?

**Comment by borxdev** [comment]
@Bizcuit, @bonhomie, It seems that the extensions **doesn't work for VSCode Windows** either.
Any ideas?
Thanks!

**Comment by Bizcuit** [comment]
Hi @borxdev and @bonhomie 
Unfortunately I don't have a windows machine to test it, but pretty sure it should work cause both windows and mac use pretty much the same code based behind.

To use this extension you either have to open a file with ".amp" extension or you need to select the AMPScript as a language at the bottom right corner of the VS Code.

Hope this makes sense to you. Let me know if you are still facing problems.
