### ISSUE TITLE
AMPscript line comments are invalid

### ISSUE THREAD

**Issue by Tocseoj** [Bizcuit/vscode-ampscript#10]
When adding comments via the 'Toggle Line Comment' (Cmd+/ on mac) command it inserts two slashes to comment the line '//' but this is not a valid comment in AMPscript. To get around this you may remove the "comments" > "lineComment" key from language-configuration.json since AMPscript doesn't have a valid Line Comment syntax so it will default to the block comment style (/* ... */)

**Comment by Bizcuit** [comment]
@Tocseoj 
Thanks a mill! Will include this in the upcoming release.

**Comment by Bizcuit** [comment]
@Tocseoj 
New version is available on the marketplace and the issue is fixed. Thanks again for letting me know!
