### ISSUE TITLE
AMPScript

### ISSUE THREAD

**Issue by majidnachan** [Bizcuit/vscode-ampscript#12]
Not able to access AMPScript file in Message content.
only __raw.readonly.json and sms.json in .jsonmessage
There should be .amp file for the SMS content that i have in Marketing cloud.

**Comment by Bizcuit** [comment]
Hi @majidnachan
That makes sense! I'll add this in the new release.

**Comment by Bizcuit** [comment]
Hi @majidnachan 
New version is now available. This functionality is now implemented. However you will notice that for some fields there are multiple files. EG: display_message_display.amp and display_message.amp. This is how MC stores it. Make sure to keep those files in sync. I'll probably implement a workaround in the new version.
