### ISSUE TITLE
highlighting breaks when backslash is used

### ISSUE THREAD

**Issue by JoernBerkefeld** [Bizcuit/vscode-ampscript#14]
Hi Sergey
think i found an issue with the syntax highlighting:
![image](https://user-images.githubusercontent.com/1917227/106288019-cdce9500-6247-11eb-82af-62b40e54aeb7.png)
similarly with `'My Contents\\'` or other combinations i tried

**Comment by Bizcuit** [comment]
@JoernBerkefeld 
Hey! You are right! Will fix this in the upcoming release.

**Comment by Bizcuit** [comment]
New version with the bug fix is now available.
