### ISSUE TITLE
Connect to Shared Content Blocks

### ISSUE THREAD

**Issue by bwhitlock01** [Bizcuit/vscode-ampscript#24]
Curious if there is a method to connecting to SFMC, then viewing and editing Shared Content Blocks, rather than content stored within each BU.
I'm not finding anything in the Connection Wizard, nor the installed Package on SFMC that enables permissions to shared content; only respective BU's.

**Comment by bwhitlock01** [comment]
+ Same question, but for Shared Data Extensions ?

**Comment by Bizcuit** [comment]
@bwhitlock01 
Shared content blocks should be easy to add. I'll have a look at it soon. Shared dataextensions is probably not so straightforward because of the way MC works with them.

**Comment by bwhitlock01** [comment]
Thanks for the feedback @Bizcuit . Shared Content blocks would be more useful than DE's anyhow. Thanks for building something so useful!

**Comment by vibesudi** [comment]
mark

**Comment by rajpc** [comment]
I am able to connect with the client id and secret. However when I select the File explorer, I am getting the error "Failed to get access token for <MID> Make sure all required access permissions are set". Any thoughts

**Comment by Devopsyleom** [comment]
> I am able to connect with the client id and secret. However when I select the File explorer, I am getting the error "Failed to get access token for Make sure all required access permissions are set". Any thoughts

Same here : 
![image](https://user-images.githubusercontent.com/43862781/163422619-4dc2fade-b351-4581-b966-417e1ee259c5.png)

**Comment by Bizcuit** [comment]
Shared content implemented in version 3.0.3. Connection related issues were discussed in a separate thread.
