### ISSUE TITLE
Errors when saving files to MC

### ISSUE THREAD

**Issue by bwhitlock01** [Bizcuit/vscode-ampscript#25]
Attempted to edit a query and save back to Marketing Cloud, though was prompted with a failed response.

Failed to save 'query.sql': Unable to write file 'mcfs://[MID]/SQL Queries/MailShrimp/Ω 🟥 HeaderNav-PRODtoDEV.query/query.sql' (Error: REST API failed)

Perhaps is this a failure based on authentication, or REST api structure? Looking for guidance. I would love to get this extension fully integrated with our MC.

**Comment by Bizcuit** [comment]
Hi @bwhitlock01 
Thanks for your comment. Are you sure that the Sql query you are trying to save is valid? MC validates the query before saving it, so it could be that there is a mistake in your sql code. Could you please try to copy the query text from the editor and try to save it directly in MC UI?

**Comment by bwhitlock01** [comment]
@Bizcuit Thanks for the details - I assume validation covers not just the SQL itself, but its source and Target data extensions for availability? I was testing on a defunct query that may not be using a Target DE that exists any longer.

I have tinkered with a good, working query and see the changes affected in the interface, so now I know the extension is generally working. :)

**Comment by Bizcuit** [comment]
@bwhitlock01 I'll add some additional error handling to show what actually went wrong while saving. But I'll close this bug report for now. BTW, did you notice that you can run the query directly from they Editor UI? And that you can filter dataextensions with a SQL like queries? I am looking at the usage stats and not too many people are using these functions. Wonder why.

**Comment by bwhitlock01** [comment]
Thanks again @Bizcuit the error handling will help a lot.
I did notice the "run query" option and started using today. Much more useful than clicking through the UI to run a couple queries manually!
