### ISSUE TITLE
Connection Issue when opening the content folders

### ISSUE THREAD

**Issue by cohuaudrey** [Bizcuit/vscode-ampscript#26]
Hello!
I am not a experimented developer but I'd like to edit the HTML and AMP script of my emails from VS code to get a better user experience. Your app seems to be great for that!
I followed all the steps for linking my MC account to VS code, the Server-to-server integration seems okay but when I try to open any folder I get this error _"Connection Issue. Failed to get a token for connection "" Check your configuration and make sure that all required permissions were set for the installed Package."_
I can't find out why. Could you help me out ? 
Thank you !
Audrey

**Comment by vibesudi** [comment]
I don't know if it can help you.
Please check:
1) permissions:
2)connect configuration
![image](https://user-images.githubusercontent.com/18044784/144963177-756e5db2-4f2b-46c8-a390-e95ec5de19fb.png)

**Comment by Bizcuit** [comment]
@cohuaudrey 
1. Make sure that your MC Package has all required permissions
2. When creating a connection in VS Code, make sure you fill all the fields. Label field can't be empty. you can use any name you want there

**Comment by juliediem** [comment]
I'm experiencing the same issue, however for me, the connection was working normally up until today. I didn't change anything on the installed package and I didn't alter the connection setup.
I double checked that the required permissions were checked off, and I filled out all the label fields.

**Comment by Bizcuit** [comment]
Hi @juliediem . That is strange. 
Try to create a new installed package and a new connection for it. Sounds like smth is wrong with your setup and not with the extension. let me know if you still have problems with it.
