### ISSUE TITLE
Missing Data Extension

### ISSUE THREAD

**Issue by EvilJordan** [Bizcuit/vscode-ampscript#28]
Within my `Dataextensions -> Triggered Sends -> MySubfolder` I have two extensions. Only one appears in the explorer, however, and I'm not sure why. Any ideas how I can debug?

**Comment by Bizcuit** [comment]
@EvilJordan 
is there smth completely different between those two? Does the one that does not show up have some special symbols in the name or a special Dataextension template was used? I can't reproduce this
