### ISSUE TITLE
I have download SQL Queries, How to find whice automation is the sql query activity in? Does it have this function？

### ISSUE THREAD

**Issue by vibesudi** [Bizcuit/vscode-ampscript#29]
1) Can I find these automation that used specific sql query through some datas or attributes?
2) Can I directly search some Keyword in VSCode instead of download datas?

**Comment by vibesudi** [comment]
Or Can I find it with some datas or attributes?

**Comment by vibesudi** [comment]
It don't include shared datas in Content Builder and Dataextensions.
 Can I load these data through some configuration?

**Comment by sagadzhanovSF** [comment]
@vibesudi sorry, none of those two are currently supported
