### ISSUE TITLE
Syntax hightlighting disabled in html comments

### ISSUE THREAD

**Issue by berkandirim** [Bizcuit/vscode-ampscript#3]
Hi @Bizcuit,
Thanks for this great extension! I have one problem. 
We often use ampscript within html files and comment out the ampscript part like:
```
<!-- %%[
 ampscript here
]%% -->

html here
```
But even if the file extension is .amp and the syntax is set to AMPscript, the part inside `<!-- -->` is treated as a comment.

How it should work:
All code within `%%[]%%` (even if it's inside an html comment) should be highlighted.

Example: Check @mmoriar1's ampscript plugin for sublime text.  https://github.com/mmoriar1/AMPScript

**Comment by Bizcuit** [comment]
Hi @berkandirim 
Happy that you guys use my extension. I've just published an updated version that should fix the issue you described. Let me know if it works as you expect so we can close this case.

**Comment by berkandirim** [comment]
Yeap, it's fixed now! Thank you :)

**Comment by Bizcuit** [comment]
@berkandirim 
Don't forget to leave a comment in Market Place if you, like this extension!
Happy Ampscripting ;)
