### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by Waldorf71** [Bizcuit/vscode-ampscript#32]
Hello!

I'm reporting a similar issue to several reported previously.

I have...
1. a new installation of VS Code (Mac)
2. followed the detailed instructions in the connection manager exactly
3. checked all permissions (both scope and BU access) are set exactly per instructions
4. checked all attributes in settings.json are correct

Clicking Connect doesn't indicate any issue, however any interaction with File Explorer returns the following error:

Connection Issue. Failed to get a token for connection "100008005"
			Check your configuration and make sure that all required 
			permissions were set for the installed Package. {"documentation":"https://developer.salesforce.com/docs/atlas.en-us.mc-apis.meta/mc-apis/error-handling.htm","errorcode":404,"message":"Not Found"} 

Really looking forward to trying this extension - any help appreciated!

**Comment by Devopsyleom** [comment]
I can't connect either, I have the following message.
However I don't see the button "Connect" in VS... Where is it located?

![image](https://user-images.githubusercontent.com/43862781/163422881-a97fcfa3-27c5-45da-a579-42f908aba23a.png)

**Comment by Bizcuit** [comment]
Hi @Devopsyleom and @Waldorf71 
Extension works so there is definitely smth wrong with your Package setup. Please make sure that:
- Your MID does not include any extra spaces at the end
- Your Auth base url looks similar to this: "https://mcaaaaa-aaaaaaaaa-aaaaaaa.auth.marketingcloudapis.com/"
- Client ID and Client Secret were copies properly and do not include any extra spaces
- Your MC Package uses a "Server-to-Server" API Integration type (not a "Web App" type)
- That package is enabled for the business unit you are trying to connect to

If all this does not help, we can have a quick screensharing session to go through your setup.

Looking forward to hear back from you!

**Comment by Bizcuit** [comment]
@Devopsyleom 
Connect button is located in the Folder Explorer tab, if you don't have any folders/workspaces opened:

![Screenshot 2022-04-23 at 13 21 57](https://user-images.githubusercontent.com/23480609/164892439-0d906210-eb47-4ddb-ab12-c6a9b5f6a587.png)

**Comment by Devopsyleom** [comment]
Hi,

Yes I am happy to have a screensharing session.
We want to use it in my company and use the version control of Github.

Please let me know how to arrange that. I am fairly available these coming
days.

Kind regards,
Yann

**Comment by Devopsyleom** [comment]
@Bizcuit , My email address is Yann@yleom.com.

Thank you

**Comment by carlsteinhilber** [comment]
Has there been any progress on this via screensharing or otherwise? I'm having the same issue.

Confirmed and re-confirmed my MID, Client ID and Client Secret are correct and have no extra spaces.
Confirmed and re-confirmed my Auth Base URL is correct, and looks similar to the example provided.
The MC package is a Server-to-Server API integration, and is enabled for all my business units.

When I initially Connect, the toaster window tells me the connection was successful, but when I try to expand any of the items in the File Explorer (such as Cloud Pages), I get the same error that everyone else is getting.

![image](https://user-images.githubusercontent.com/4267686/167004428-680557fc-deda-4fc5-87ce-cbe9a923218c.png)

All permissions are set on the package exactly as recommended

![image](https://user-images.githubusercontent.com/4267686/167004912-b8e874c7-83a6-44c0-8d4e-81c040289dbc.png)

Though I notice "Access" is set to "Offline Access". Not sure if this is normal, and if not, how to change it.

**Comment by Bizcuit** [comment]
@Devopsyleom @carlsteinhilber @Waldorf71 
Could you please do the following:
1. Connect and try to open one of the folders
2. Wait for the error message to show up
3. In the top menu of VS Code select View -> Output (check screenshots below)
4. An output panel will show up at the bottom of the screen. 
5. Select "MCFS" from the dropdown on the right side of the panel (check screenshot)
6. It will include detailed debug output. 
7. DO NOT POST THE FULL OUTPUT HERE, IT INCLUDES YOUR TOKEN INFORMATION
8. Find the line that starts with "innerException". below you should see error messages returned by MC (line starts with "message"). 
9. Share the message text here
10. DO NOT POST THE FULL OUTPUT HERE, IT INCLUDES YOUR MC TOKEN INFORMATION
<img width="505" alt="Screenshot 2022-05-06 at 23 43 44" src="https://user-images.githubusercontent.com/23480609/167221109-e6fb2fbe-f0e2-46df-9b27-1105865cf8c3.png">

<img width="1019" alt="Screenshot 2022-05-06 at 23 45 43" src="https://user-images.githubusercontent.com/23480609/167221137-6cdac497-bb2e-489e-ae79-d7f24ed92ebe.png">

**Comment by carlsteinhilber** [comment]
This is what I see in the Output panel under MCFS:

`  "message": "Connection Issue",
  "details": "Failed to get a token for connection \"[my MID]\"\n\t\t\tCheck your configuration and make sure that all required \n\t\t\tpermissions were set for the installed Package",
  "innerException": {
    "message": "Cannot set headers after they are sent to the client",
    "name": "Error",`

**Comment by Bizcuit** [comment]
@carlsteinhilber 
Thanks a lot! What's your OS? Windows, Mac or Linux?

**Comment by carlsteinhilber** [comment]
Windows 10 Professional.

**Comment by Bizcuit** [comment]
@carlsteinhilber 
thanks! it look like a windows specific bug in one of the libraries used internally by the project. 
I'll work on this during this weekend

**Comment by carlsteinhilber** [comment]
Hi @Bizcuit 
Were you able to make any progress on this? Anything more I can provide?
Thanks!

**Comment by ChanKhath** [comment]
Any updates?

**Comment by guivlm** [comment]
I'm trying to connect to my Marketing Cloud account by using the connection manager and I'm getting the same issue.
I've followed the steps above and checked for all permissions.
I'm using macOS Monterrey. 

The visual studio log gives me the following info:

`2022-06-22T18:56:38.942Z => ERROR ********************************************
2022-06-22T18:56:38.942Z => Connection Issue. Failed to get a token for connection ""
			Check your configuration and make sure that all required 
			permissions were set for the installed Package. 
2022-06-22T18:56:38.942Z => {
  "message": "Connection Issue",
  "details": "Failed to get a token for connection \"\"\n\t\t\tCheck your configuration and make sure that all required \n\t\t\tpermissions were set for the installed Package",
  "innerException": {
    "message": "connect ECONNREFUSED 127.0.0.1:80",
    "name": "Error",
    "stack": "Error: connect ECONNREFUSED 127.0.0.1:80\n\tat TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)",
    "config": {
      "url": "v2/token",
      "method": "post",
      "data": "{\"name\":\"my connection 1\",\"account_id\":\"\",\"authBaseUri\":\"\",\"client_id\":\"\",\"client_secret\":\"\",\"grant_type\":\"client_credentials\"}",
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json",
        "User-Agent": "axios/0.21.1",
        "Content-Length": 127
      },
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1
    },
    "code": "ECONNREFUSED"
  }
}
2022-06-22T18:56:38.942Z => **************************************************
`

**Comment by Bizcuit** [comment]
@guivlm 
based on the error, you connection is not configured at all.

- open connection manager (screenshot below)
- click new connection
- fill all required fields (label, mid, Auth Base Uri, Client ID, Client Secret)
- click SAVE to save the connection string
- now click connect

**Comment by Bizcuit** [comment]
@guivlm 
could you please: 
-  go to Main menu => Preferences => Settings
- type "Mcfs: Connections" in the search field
- Click "edit settings JSON" next to "Mcfs: Connections" 
- a JSON file with your connections will open up. Please check the "mcfs.connections" array. Is it empty? does it have just one row?

**Comment by guivlm** [comment]
@Bizcuit Issue solved, I don't know why, but the connection didn't reflect the primary folder name.
I've had deleted the main folder and setup the connection again. It's working right now.

Thank you for the help!

**Comment by Bizcuit** [comment]
@carlsteinhilber @Waldorf71 @Devopsyleom 
Hi all.
I've just updated vs-code extension for MC. Could you please check if you still have the issue with the connection?
Thanks a lot in advance!

**Comment by CSteinhilber** [comment]
Unfortunately, still the same issue.

I uninstalled and reinstalled the extension, confirmed it is v3.0.3. Went ahead and deleted and recreated the connection. The initial connection is successful, but when I try to access any of the folders I get the same error message.

`"details": "Failed to get a token for connection \"[mymid]\"\n\t\t\tCheck your configuration and make sure that all required \n\t\t\tpermissions were set for the installed Package",
  "innerException": {
    "message": "Cannot set headers after they are sent to the client",
    "name": "Error",
    "stack": "Error: Cannot set headers after they are sent to the client\n\tat new NodeError`... etc

**Comment by Bizcuit** [comment]
@CSteinhilber thanks a lot for your prompt reply. I think I found the root-cause this time. Version 3.0.4 is on its way to vscode extensions marketplace. I would really appreciate if you could test it once again and let me know if it works. I am not able to reproduce this issue so has to rely on feedback from people facing it. Sorry for that.

**Comment by CSteinhilber** [comment]
> I am not able to reproduce this issue so has to rely on feedback from people facing it. Sorry for that.

Totally get that. Faced the same myself.

Unfortunately, I've loaded up v3.0.4, and still get the same error when opening the folders. Wondering if it's an issue with proxy, or perhaps 2FA?

**Comment by CSteinhilber** [comment]
I'm either working on-prem or remotely via VPN, so IP should already be allowed at MC. I've been using the SFMC API (different integration point) for other projects from the same IP with no issue. But I am unable to disable firewalls and/or proxies, unfortunately.

I am able to request an Auth token via Postman from the same machine and IP.

I think I'll just have to chalk it up to firewall/proxy issues. Such a shame.

**Comment by Bizcuit** [comment]
@CSteinhilber 
Thanks a lot for your help. Last try, I promise. I added some very chatty logs. Could you please:

1. Download the file attached to this post 
2. Remove ".zip" from the file name. File should have a ".vsix" extension
3. Remove current version of the extension 
4. On the extensions panel in VS Code click "three dots" button at the top right corner (check screenshot below) 
5. Select "Install from VSIX" and select the downloaded file
6. Try to connect and check the logs. Would be great to get those logs without any sensitive information. you can send it to agadzhanov(at)gmail.com

<img width="631" alt="Screenshot 2022-06-25 at 00 25 58" src="https://user-images.githubusercontent.com/23480609/175719048-4709696a-8445-4e8d-ba48-1c016bf7f504.png">

ATTACHEMENT:
[ampscript-3.0.5.vsix.zip](https://github.com/Bizcuit/vscode-ampscript/files/8981764/ampscript-3.0.5.vsix.zip)

PS: attached "vsix" file is just an extension file. Technically it's just a zip file and you can easily open it to make sure that it's simply the same extension with some additional logging.

**Comment by Bizcuit** [comment]
I did a small research. VSCode currently does not support automatic proxy setup based on system configuration for extensions. 
However there is a manual config that you can set directly in VSCode setup and I think it's worth trying.

[Documentation](https://code.visualstudio.com/docs/setup/network#_legacy-proxy-server-support)

In VSCode:
- go to Preferences => Settings
- search for "proxy"
- set the "Http: Proxy" setting

Based on your logs, "Proxy-Authorization" header is already sent with every request. So connection string is the only thing you'll have to set.
 
Connection String should look like that for http proxy:
http://USERID:PASSWORD@proxy.com:3128
or like that for https proxy
https://USERID:PASSWORD@proxy.com:3128

I don't think that you even need to specify userid and password in the connection string, because of the "Proxy-Authorization" header that is already sent, but worth trying both options: with and without.

![Screenshot 2022-06-25 at 10 56 37](https://user-images.githubusercontent.com/23480609/175766227-fbe2cab5-060c-402e-ae85-683e1aa14994.png)

**Comment by carlsteinhilber** [comment]
Thank you for the extra research, you are amazing!

Unfortunately, still no joy here.

I tried the friendly settings, still the same error.

Then I tried opening the settings.json and added both an http_proxy and https_proxy, and set proxyStrictSSL to false as per the discussion here https://stackoverflow.com/questions/37730040/how-to-specify-a-user-id-and-password-for-visual-studio-code-with-an-authenticat

Still the same error.

Even tried setting the proxyAuthorizatrion with a base64 basic string, but still same error.

I don't think we'll be able to work around this, unfortunately.

**Comment by Bizcuit** [comment]
@carlsteinhilber 
Sorry for asking to do this one more time, but I did some more reading about the topic. Looks like VS Code team is doing some extra magic with the standard node HTTP/HTTPS modules to support Proxies out of the box and I have a feeling that the reason why it does not work is because of the AXIOS library that I was using to make API calls to MC (that tries to do some extra proxy magic on top). So I changed the core method to do API calls and it now does not use AXIOS at all. Just hardcore HTTP/HTTPS modules of node.  

I would really appreciate if you could find a few minutes to try a new version attached to this post using [instructions](https://github.com/Bizcuit/vscode-ampscript/issues/32#issuecomment-1165994620) that I shared earlier

Would be great to understand two things:
- does it work **without** VS Code proxy config
- does it work **with** the VS Code proxy config

Thanks a lot in advance
[ampscript-3.1.0.vsix.zip](https://github.com/Bizcuit/vscode-ampscript/files/9274844/ampscript-3.1.0.vsix.zip)
!

**Comment by carlsteinhilber** [comment]
Wow! That's actually working! I can now connect to our SFMC with no errors in the console!

Http: Proxy (Settings) is empty
Http: Proxy Strict SSL (Settings) is on
Http: ProxySupport (Settings) is on
Http: ProxyAuthorization (JSON) is currently set to null.

This is amazing! Thank you

**Comment by Bizcuit** [comment]
@carlsteinhilber

Fantastic news! I'll prepare the release and will push the fix to the marketplace. Thanks a lot for all your help!

Regarding shared dataextension... yeah... it's a bit tricky with shared DEs... I would say it's one the existing gaps. 

The rest works fine?

PS: I hope you don't mind if I add some credits to you in the release notes.

**Comment by carlsteinhilber** [comment]
> Regarding shared dataextension... yeah... it's a bit tricky with shared DEs... I would say it's one the existing gaps.

I hope you find a way. Nearly all of the important DE's in our organization are Shared DE's, unfortunately. I assume the only workaround for now is to run a query that saves the data to a regular DE as a temp.

> The rest works fine?

Seems to, yes. I'm able to view DE columns.json and rows.csv/json, view Scripts, view and run Queries, view _and edit_ Cloud Pages, view Content and Shared Content... if there's something specific you'd like me to test, that makes more complicated use of the connection, let me know.

**Comment by Bizcuit** [comment]
@carlsteinhilber 
Awesome! that's more than enough. Thanks a lot for your help. I'll have a look into shared DEs next week

**Comment by Bizcuit** [comment]
Connection issues were most probably related to the usage of corporate proxy server. Latest version v3.0.5 solves this problem
