### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by Devopsyleom** [Bizcuit/vscode-ampscript#33]
I have installed the packaged and set it up as advised.
I have set the right permissions in the package and edited the json file with AuthBaseUri, client_id, client_secret.
But I get the following message 

![image](https://user-images.githubusercontent.com/43862781/163420222-b26b1177-702f-4e5f-83ec-3b49d10d0b3c.png)

**Comment by Bizcuit** [comment]
@Devopsyleom why is your connection name/label empty. Why did you have to edit a JSON file, instead of using a connection manager to create a new connection?
![Screenshot 2022-04-23 at 13 28 27](https://user-images.githubusercontent.com/23480609/164892646-c614b117-762c-4d49-b9fa-223ce72f9a5e.png)

**Comment by Devopsyleom** [comment]
You are absolutely right. I couldn't locate "Connection Manager" initially.
Then I used Connection Manager following all the steps you mentioned
regarding creating the package and creating a new connection in VS. But it
still tells me that it can't connect.

Kind regards,
Yann
