### ISSUE TITLE
Unable to Write to Marketing Cloud

### ISSUE THREAD

**Issue by austinmscholl** [Bizcuit/vscode-ampscript#37]
Hi,

After connecting MCFS to my marketing cloud org, is there some additional action (beyond saving a file), I need to take to push my changes to the production MC Org?

**Comment by Bizcuit** [comment]
Hi, @austinmscholl 
No, nothing else is required. I guess you did not get an error message after saving. As far as I understand you see the list of assets, can open a file and save it, but changes are not reflected in MC (please correct me if i'm wrong). Each asset is presented as multiple files. Which one are you trying to modify?

**Comment by Bizcuit** [comment]
no reply. unable to reproduce
