### ISSUE TITLE
Support for Journey Builder and Automations 

### ISSUE THREAD

**Issue by softwareengineer7777** [Bizcuit/vscode-ampscript#38]
I used your extension to download everything that I could by following the directions that came with the extension.  I then uploaded these files to Github.  When I showed the SFMC team what now resides in Github, I was told that they didn't see Journeys or Automations.  As a Salesforce Developer, I have no idea what SFMC files should look like and how they are structured.  So my first question is, do you support Journeys and Automations?  I assume they'd be top level if they were supported, but maybe they're buried somewhere in the structure that I don't know of.  If you don't support Journeys and Automations, do you plan on supporting them?  If so, any idea when they would be supported?  I need this fairly immediately, so if you aren't supporting them any time soon, do you know of any of tools I could use to get SFMC metadata and import it into Github?  Much appreciated.

**Comment by Bizcuit** [comment]
Hi @softwareengineer7777 
My tool does not support Journeys and Automations. No plans to do that. The goal of this VS Code extension is to give developers an easy way to work with MC assets using IDE-like environment.

If your goal to is sync files to github, you can check this project:
https://github.com/Accenture/sfmc-devtools
