### ISSUE TITLE
Marketing Cloud API credential storage

### ISSUE THREAD

**Issue by mikantlin** [Bizcuit/vscode-ampscript#4]
Hi, was just wondering exactly how the Marketing Cloud API credentials are stored by Connection Manager? The documentation wasn't particularly clear about that.

**Comment by Bizcuit** [comment]
Hi @mikantlin 
All connection are stored in the global settings of your VSCode. Just open Preferences->Setting from your top menu and search for MCFS. You'll find a JSON definition of each connection string. Unfortunately it is stored as raw text. It does not make much sense to encrypt this data as the encryption key will be also sitting somewhere in the code of the extension. An alternative would be to use MC OAuth integration, but in this case this solution would require an external server.
Hope this makes sense.
