### ISSUE TITLE
SOAP Api errors

### ISSUE THREAD

**Issue by softwareengineer7777** [Bizcuit/vscode-ampscript#40]
When downloading Data Extensions, I keep running into SOAP timeout errors.  I think the reason is because a timeout is hit when downloading all of the data as some of the tables are pretty massive.  Since I'm only interested in retrieving the data extension's metadata, is there a way to tell your VS Code extension to not download that actual data from SFMC?

**Comment by Bizcuit** [comment]
Hi @softwareengineer7777 
The actual records are only downloaded when you try to open a CSV file of the dataextension and it's limited to 2000 records, so I don't think this is the issue. When exactly do you get a timeout error? Does the editor show you the dataextension folder structure? Does it show you the list of dataextensions in a folder?
thanks a lot in advance!

**Comment by softwareengineer7777** [comment]
I can see the structure, and I also see that the csv isn't downloaded until
I open a csv.  What I'm trying to do is download the data extensions (right
click Dataextensions and click Download...), so I can push them to Github.
When I do this, it downloads the csv as well as all the other metadata.
Some of the csv files can be massive, so it's causing SOAP timeout errors.
We really don't want csv files in Github, so if there was an option to not
download the csv file, I think it would help in multiple ways.  First, we
keep personal contact information out of Github.  Second, it should take
care of the timeout issues since we aren't pulling all of that unnecessary
data.

[image: Screenshot 2023-04-13 at 10.57.55 AM.png]

**Comment by Bizcuit** [comment]
Ah... I see... so you are pretty much trying to save the data locally, VSCode tries to get content of all files, including CSVs and timesout. What if the api timeout is increased to make sure that issue is gone and then you can add a filter for CSV files in your .gitignore? Will that work for you?

**Comment by softwareengineer7777** [comment]
Ah, that's a bummer.  I know the REST API for downloading Journey data
allows you to select what information you want.  I haven't dug into the
SOAP APIyet, but I was hoping there would be some option like that.  I've
already added the filter to .gitignore, so increasing the timeout would
definitely be helpful.  As I mentioned though, those CSV files can be huge,
so are you going to max out the timeout?  Or can you make it an adjustable
setting, so others aren't affected by the change?
