### ISSUE TITLE
REST API failed. unable to get local issuer certificate.

### ISSUE THREAD

**Issue by prateekbhardwaj123** [Bizcuit/vscode-ampscript#42]
Getting below error  many times .Sometimes it gets connected well sometimes it gives below error. 

REST API failed. unable to get local issuer certificate.

**Comment by Bizcuit** [comment]
I am pretty sure this is related to your proxy settings. Sorry... there is pretty much nothing I can do here. Proxy configs are very different and it will be hard to find your specific problem
