### ISSUE TITLE
Possibility of "Publishing" Cloud Pages

### ISSUE THREAD

**Issue by SAC-ia** [Bizcuit/vscode-ampscript#43]
Hi, I noticed that there was an issue from 2020 talking about the possibility of "publishing" Cloud Pages from the editor, but the response was that the MC API does not allow for publishing, but now that it's been around 3 years, I been seeing articles talking about this extension able to publish now, yet I can't seem to do it. Has this been implemented at all recently, or is it still impossible due to MC API's limitations? Thank you for reading.

**Comment by Waldorf71** [comment]
Same experience here. Is it possible to publish Cloud Pages from VS Code? If so, how?

**Comment by Bizcuit** [comment]
@SAC-ia , @Waldorf71 
This is still not possible with public MC APIs. 
Sorry
