### ISSUE TITLE
Clarification on where credentials are stored when supplied to the extension

### ISSUE THREAD

**Issue by chris-mathews-gc** [Bizcuit/vscode-ampscript#44]
More clarification on where the credentials are stored when supplied to the extension - are they stored locally? If so where?

**Comment by Bizcuit** [comment]
@chris-mathews-gc 
credentials are stored locally in the vscode extension setting. Opem Main Menu => Settings => Extensions and search for "mcfs.connections". You'll find your connection strings. 
Credentials are never transferred to third-party servers.
