### ISSUE TITLE
Possibility to view and edit file resources

### ISSUE THREAD

**Issue by HamzaBichara** [Bizcuit/vscode-ampscript#47]
Hi,

Is there any possibility to view and edit file resources? for now only cloudpages are available for view and edit.

Thank you!

**Comment by Bizcuit** [comment]
Hi @HamzaBichara 
I don't think I understand your question. 
You can edit almost all files available in the editor including: Content blocks, Dataextensions, SQL queries etc. The only files that you are not allowed to edit are the ones where you can find ".readonly." in the filename. EG: _columns.readonly.json of a dataextension. 

If you get error messages trying to save other file types, then most probably you have done smth wrong with the Installed Package permissions.
