### ISSUE TITLE
Publish Cloud Page

### ISSUE THREAD

**Issue by AlexGladding** [Bizcuit/vscode-ampscript#48]
Is it possible to publish a CloudPage from VS Code? I can save the content.amp resource, but I am not finding an obvious way to publish after saving. Thanks in advanced. 

PS: Great app! It's already saving me a ton of time.

**Comment by Bizcuit** [comment]
Unfortunately there are no public APIs to publish cloudpages.

Sorry.

**Comment by AlexGladding** [comment]
Thanks for the reply! Appreciate you looking into it. Nice work on the app, it's been a huge timesaver since I started using it.

Thanks care,
Alex
________________________________
