### ISSUE TITLE
MCFS Connection manager doesn't open contents

### ISSUE THREAD

**Issue by VijayaSankarN** [Bizcuit/vscode-ampscript#5]
Thanks for the extension. Was able to establish connection with my Marketing Cloud account using VS Code. In the explorer, all the contents are also listed. But when I open, it says:
![image](https://user-images.githubusercontent.com/12524485/92473220-0a95e300-f1f8-11ea-9063-572c3b089bd3.png)

It is not just for cloud page, for every file type like blocks, emails, templates it says the same error.

This is Windows 10 with updated VS Code version. Extension is also upto date. Am administrator of my machine and have all folder permissions.

**Comment by Bizcuit** [comment]
Hi @VijayaSankarN 
Thanks a lot for the bug report. I think I know what this problem is about. I didn't test it on Windows and it seems that the problem is because windows uses "\" as a path separator, when all other platforms use "/". I'll fix it tonight and will push an update to the VSCode Marketplace. Will let you know in this thread when it's done, so you can test it.
Appreciate your help!

**Comment by Bizcuit** [comment]
Hi @VijayaSankarN 

This bug should now be fixed. Could you please make sure that the extension was updated to the latest version (2.0.2) and give it another try? If I don't hear back from you in a couple of days, I'll close this issue.

Thanks a lot for letting me know!

PS: Share your ideas using [this form](https://docs.google.com/forms/d/e/1FAIpQLSc8NCJcqTxMIIJ5J1pWKTnPY2JewvTS8GU6b9-Lvhdze1N4RA/viewform?usp=sf_link), leave your feedback on the [Extension Page](https://marketplace.visualstudio.com/items?itemName=sergey-agadzhanov.AMPscript) or add a star on my [github repository](https://github.com/Bizcuit/vscode-ampscript).

**Comment by VijayaSankarN** [comment]
Perfect @Bizcuit! It was a faster solution!! Thanks much.

_For documentation:_
Updated the extension, removed the folder from the workspace, reconnected the VS code to my Marketing Cloud.
