### ISSUE TITLE
Unable to connect to SFMC

### ISSUE THREAD

**Issue by dgurtubay** [Bizcuit/vscode-ampscript#7]
Hi,

I am getting this error 'Unable to read directory "/visual/visual" Error details: Error: Incorrect MID'

I have checked the MID and is fine, I have grant access to all BUs.

I have created a login access with postman with the same MID and credentials, and this URI https://xxxxxxxxxxxxxxxxxxxxxxxxx.auth.marketingcloudapis.com/v2/token instead of https://xxxxxxxxxxxxxxxxxxxxxxxxx.auth.marketingcloudapis.com/ and is giving me an status Ok 200

Any advise with this error?

Thank you

Daniel

**Comment by dgurtubay** [comment]
I have seen also that the connection name does not change from My Connection1. I have saved changed, reopen VS and the json has the values I entered but the side bar doesn't get not even the connection name.

**Comment by Bizcuit** [comment]
Hey @dgurtubay 
From the error message it looks like smth is wrong with your MID. Could you please have a look at the screenshot below and let me know if your config looks similar to it?
123456 - in this example is the MID. It can only include numbers and can be found at the right top corner of MC when you mouse hover the Business Unit name.

![Screenshot 2020-10-30 at 17 55 23](https://user-images.githubusercontent.com/23480609/97734193-1ce61c00-1ad9-11eb-9f46-4791eca31f55.png)

**Comment by dgurtubay** [comment]
Thank you for your answer.

I think I am filling everything right. This is the setting.json that creates the extension:
{
    "mcfs.notifications": {
        "hasOpenedConnectionManager": true,
        "hasConnectedToMC": true,
        "dontShowConnectionManagerAlert": false,
        "hasShownChangelog": true
    },
    "mcfs.connections": [
        {
            "name": "Atmira",
            "account_id": "10960401",
            "authBaseUri": "https://XXXXXXXXXXXXx.auth.marketingcloudapis.com/",
            "client_id": "XXXXXXXXXXXX",
            "client_secret": "XXXXXXXXXXXX",
            "grant_type": "client_credentials"
        }
    ]
}

I am writing only the numbers of the MID. 
Other thing I noticed is that 'name':Atmira' does not show in the Explorer, it still naming it MyConnection1

I seems like in some way it does not save some of the values. But after closing VS, I open it again everything is save in the settings.

If I do click connection, and then go to the explorer and try to create a file/folder I get this message 'Unable to create file 'mcfs:/Visual' that already exists when overwrite flag is not set'

Thank you

**Comment by Bizcuit** [comment]
Hi @dgurtubay
Could you please right click this wrong connection name (MyConnection1) in the file explorer (not in connection manager)  and then select "Remove Folder from workspace". Then go back to connection manager and click connect.

**Comment by dgurtubay** [comment]
Hi, 

Yes, after deleting MyConnection1, I could connect perfectly to SFMC.

Thanks a lot!
