### ISSUE TITLE
[Question] Is there any way to "publish" cloud pages from the editor?

### ISSUE THREAD

**Issue by datawebbie** [Bizcuit/vscode-ampscript#8]
First of all, thanks for the great plug-in! I really love it and it works well.

Is there any way to publish cloud pages from the editor? I can see the publish permission is given to the connection setting.

**Comment by Bizcuit** [comment]
hey @datawebbie! 
Thanks for your warm words. This functionality is planned for future releases. Main problem is that there are currently no public MC APIs for that. I'll close this issue for now, but hopefully you'll find this function soon.
